local o = vim.opt
vim.g.mapleader = ' '
o.expandtab = true
o.shiftwidth = 4
o.tabstop = 4
o.softtabstop = 4
o.autoindent = true
o.smartindent = true
o.wrap = false
o.number = true
o.relativenumber = true
o.ignorecase = true
o.smartcase = true
o.clipboard = 'unnamedplus'
o.scrolloff = 16
o.undofile = true
o.swapfile = false
o.backup = false
o.incsearch = true
o.inccommand = "split"
o.termguicolors = true
o.background = "dark"
o.signcolumn = "yes"
o.splitright = true
o.splitbelow = true
o.updatetime = 50
o.colorcolumn = "80"
o.hlsearch = true
o.mouse = "a"
vim.g.editorconfig = true
o.list = true
o.listchars = {
  tab = '» ',       -- Displays for tabs (must be 2 characters)
  space = '·',      -- Displays for regular spaces
  multispace = '·', -- Displays for consecutive spaces
  lead = '·',       -- Displays for leading spaces
  trail = '•',      -- Displays for trailing spaces
  nbsp = '␣',       -- Displays for non-breaking spaces
}

